// Decompiled by Serious. Credits to Scoba for his original tool, Cerberus, which I heavily upgraded to support remaining features, other games, and other platforms.
#using scripts\cp\_dialog;

#namespace namespace_c1b94c1e;

/*
	Name: init_voice
	Namespace: namespace_c1b94c1e
	Checksum: 0x1815A6A5
	Offset: 0x1328
	Size: 0xC04
	Parameters: 0
	Flags: Linked
*/
function init_voice()
{
	dialog::add("plyz_the_pieces_were_comi_0", "vox_zram_1_01_000_plyz");
	dialog::add("plyz_hendricks_was_unhing_0", "vox_zram_1_01_001_plyz");
	dialog::add("plyz_kane_came_with_she_0", "vox_zram_1_01_002_plyz");
	dialog::add("plyz_we_weren_t_ready_for_0", "vox_zram_1_01_003_plyz");
	dialog::add("plyz_this_place_if_the_0", "vox_zram_1_01_004_plyz");
	dialog::add("plyz_you_certainly_weren_0", "vox_zram_2_01_000_plyz");
	dialog::add("salm_you_say_it_like_i_ha_0", "vox_zram_2_01_001_salm");
	dialog::add("plyz_with_no_time_we_nee_0", "vox_zram_2_01_002_plyz");
	dialog::add("plyz_the_truth_serum_w_0", "vox_zram_2_01_003_plyz");
	dialog::add("plyz_he_asked_about_taylo_0", "vox_zram_2_01_004_plyz");
	dialog::add("salm_and_i_told_him_as_i_0", "vox_zram_2_01_005_salm");
	dialog::add("plyz_like_puppets_on_stri_0", "vox_zram_2_01_006_plyz");
	dialog::add("salm_the_undead_are_mindl_0", "vox_zram_2_01_007_salm");
	dialog::add("plyz_hendricks_wanted_to_0", "vox_zram_2_01_008_plyz");
	dialog::add("salm_for_many_years_i_had_0", "vox_zram_2_01_009_salm");
	dialog::add("salm_but_he_had_been_pull_0", "vox_zram_2_01_010_salm");
	dialog::add("plyz_the_demigoddess_his_0", "vox_zram_2_01_011_plyz");
	dialog::add("salm_a_pawn_in_a_much_lar_0", "vox_zram_2_01_012_salm");
	dialog::add("plyz_you_you_told_him_0", "vox_zram_2_01_013_plyz");
	dialog::add("salm_how_does_one_kill_a_0", "vox_zram_2_01_014_salm");
	dialog::add("plyz_is_to_open_the_ga_0", "vox_zram_2_01_017_plyz");
	dialog::add("salm_as_we_are_doing_now_0", "vox_zram_2_01_018_salm");
	dialog::add("plyz_hendricks_told_us_to_1", "vox_zram_2_01_021_plyz");
	dialog::add("plyz_the_assault_on_ramse_0", "vox_zram_3_01_000_plyz");
	dialog::add("plyz_we_didn_t_have_time_0", "vox_zram_3_01_001_plyz");
	dialog::add("plyz_it_was_a_simple_str_0", "vox_zram_4_01_000_plyz");
	dialog::add("plyz_something_knocked_ou_0", "vox_zram_4_01_001_plyz");
	dialog::add("plyz_cairo_she_was_a_cit_0", "vox_zram_4_01_002_plyz");
	dialog::add("plyz_our_triggerman_got_h_0", "vox_zram_5_01_000_plyz");
	dialog::add("plyz_khalil_thanked_us_0", "vox_zram_6_01_000_plyz");
	dialog::add("plyz_egyptian_army_comman_0", "vox_zram_6_01_001_plyz");
	dialog::add("plyz_i_gave_hendricks_a_h_0", "vox_zram_7_01_001_plyz");
	dialog::add("salm_you_went_in_to_save_0", "vox_zram_7_01_002_salm");
	dialog::add("plyz_does_that_matter_0", "vox_zram_7_01_003_plyz");
	dialog::add("plyz_we_d_cleared_the_pla_0", "vox_zram_8_01_000_plyz");
	dialog::add("salm_what_did_you_hear_1", "vox_zram_8_01_001_salm");
	dialog::add("plyz_nothing_and_that_wa_0", "vox_zram_8_01_002_plyz");
	dialog::add("plyz_something_had_taken_0", "vox_zram_8_01_003_plyz");
	dialog::add("plyz_we_saw_reinforcement_0", "vox_zram_8_01_004_plyz");
	dialog::add("plyz_we_got_out_of_the_op_0", "vox_zram_8_01_005_plyz");
	dialog::add("plyz_it_wasn_t_just_the_c_0", "vox_zram_1_02_000_plyz");
	dialog::add("plyz_between_the_flesh_ea_0", "vox_zram_1_02_001_plyz");
	dialog::add("salm_for_that_very_reason_0", "vox_zram_1_02_002_salm");
	dialog::add("plyz_why_what_were_you_r_0", "vox_zram_1_02_003_plyz");
	dialog::add("salm_from_the_creature_yo_0", "vox_zram_1_02_004_salm");
	dialog::add("plyz_he_didn_t_say_it_bu_0", "vox_zram_3_02_001_plyz");
	dialog::add("plyz_turns_out_it_wasn_t_0", "vox_zram_4_02_000_plyz");
	dialog::add("plyz_cairo_was_no_man_s_l_0", "vox_zram_4_02_001_plyz");
	dialog::add("plyz_i_put_him_in_his_pla_0", "vox_zram_4_02_002_plyz");
	dialog::add("plyz_i_grabbed_the_spike_0", "vox_zram_4_02_003_plyz");
	dialog::add("plyz_we_detonated_the_las_0", "vox_zram_4_02_004_plyz");
	dialog::add("plyz_i_told_hendricks_i_n_0", "vox_zram_5_02_000_plyz");
	dialog::add("plyz_good_thing_hendricks_0", "vox_zram_5_02_001_plyz");
	dialog::add("plyz_there_were_so_few_of_0", "vox_zram_7_02_000_plyz");
	dialog::add("plyz_i_d_take_it_0", "vox_zram_7_02_001_plyz");
	dialog::add("plyz_he_pulled_his_piece_0", "vox_zram_7_02_002_plyz");
	dialog::add("salm_strange_even_with_0", "vox_zram_7_02_003_salm");
	dialog::add("salm_he_clung_to_life_wit_0", "vox_zram_7_02_004_salm");
	dialog::add("plyz_turns_out_it_didn_t_0", "vox_zram_7_02_005_plyz");
	dialog::add("plyz_he_didn_t_survive_th_0", "vox_zram_7_02_006_plyz");
	dialog::add("plyz_and_there_it_was_th_0", "vox_zram_8_02_001_plyz");
	dialog::add("plyz_kane_came_over_comms_0", "vox_zram_8_02_002_plyz");
	dialog::add("plyz_khalil_agreed_to_com_0", "vox_zram_8_02_003_plyz");
	dialog::add("salm_and_hendricks_0", "vox_zram_8_02_004_salm");
	dialog::add("plyz_his_mind_was_melting_0", "vox_zram_8_02_005_plyz");
	dialog::add("plyz_he_didn_t_like_that_0", "vox_zram_8_02_006_plyz");
	dialog::add("salm_he_attacked_you_0", "vox_zram_8_02_007_salm");
	dialog::add("plyz_i_told_you_it_wasn_0", "vox_zram_8_02_008_plyz");
	dialog::add("salm_what_did_he_say_0", "vox_zram_8_02_010_salm");
	dialog::add("dolo_salim_lies_0", "vox_zram_8_02_011_dolo");
	dialog::add("plyz_he_didn_t_think_open_0", "vox_zram_8_02_012_plyz");
	dialog::add("plyz_are_you_0", "vox_zram_8_02_013_plyz");
	dialog::add("plyz_we_weren_t_ready_for_1", "vox_zram_3_03_000_plyz");
	dialog::add("plyz_safiya_square_was_a_0", "vox_zram_7_03_000_plyz");
	dialog::add("plyz_it_didn_t_take_long_0", "vox_zram_7_03_001_plyz");
	dialog::add("plyz_it_was_only_a_matter_0", "vox_zram_7_03_002_plyz");
	dialog::add("plyz_he_was_done_he_was_0", "vox_zram_8_03_001_plyz");
	dialog::add("plyz_he_wasn_t_buying_thi_0", "vox_zram_8_03_002_plyz");
	dialog::add("plyz_he_wasn_t_buying_thi_1", "vox_zram_8_03_003_plyz");
	dialog::add("plyz_khalil_was_waiting_0", "vox_zram_1_04_000_plyz");
	dialog::add("salm_how_was_khalil_happ_0", "vox_zram_1_04_001_salm");
	dialog::add("plyz_it_wasn_t_a_warm_wel_0", "vox_zram_1_04_002_plyz");
	dialog::add("salm_he_was_angry_0", "vox_zram_1_04_003_salm");
	dialog::add("plyz_he_was_tired_tired_0", "vox_zram_1_04_004_plyz");
	dialog::add("salm_what_was_coming_0", "vox_zram_1_04_005_salm");
	dialog::add("plyz_extinction_beat_0", "vox_zram_1_05_000_plyz");
	dialog::add("plyz_khalil_s_rage_wasn_t_0", "vox_zram_1_05_001_plyz");
	dialog::add("salm_what_did_you_hope_to_0", "vox_zram_1_05_002_salm");
	dialog::add("plyz_how_to_stop_deimos_0", "vox_zram_1_05_003_plyz");
	dialog::add("plyz_kane_asked_what_was_0", "vox_zram_1_05_004_plyz");
	dialog::add("plyz_the_dead_were_moving_0", "vox_zram_1_05_006_plyz");
	dialog::add("plyz_that_set_hendricks_o_0", "vox_zram_1_05_007_plyz");
	dialog::add("salm_how_did_khalil_respo_0", "vox_zram_1_05_008_salm");
	dialog::add("plyz_wa_command_was_down_0", "vox_zram_1_05_009_plyz");
	dialog::add("plyz_khalil_led_us_to_int_0", "vox_zram_1_06_000_plyz");
	dialog::add("plyz_but_if_we_could_get_0", "vox_zram_1_06_001_plyz");
}

